<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-RVDMUTME" name="com.qa.EmployeeAPI.TestCase.TC001_Get_All_Employees" tests="9" failures="2" timestamp="10 Feb 2020 19:45:03 GMT" time="0.014" errors="0">
  <testcase name="checkResponseTime" time="0.003" classname="com.qa.EmployeeAPI.TestCase.TC001_Get_All_Employees"/>
  <testcase name="checkserverType" time="0.002" classname="com.qa.EmployeeAPI.TestCase.TC001_Get_All_Employees">
    <failure type="java.lang.AssertionError" message="expected:&lt;nginx/1.16.0&gt; but was:&lt;nginx/1.14.1&gt;">
      <![CDATA[java.lang.AssertionError: expected:<nginx/1.16.0> but was:<nginx/1.14.1>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
at com.qa.EmployeeAPI.TestCase.TC001_Get_All_Employees.checkserverType(TC001_Get_All_Employees.java:89)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkserverType -->
  <testcase name="checkContentLenght" time="0.000" classname="com.qa.EmployeeAPI.TestCase.TC001_Get_All_Employees"/>
  <testcase name="checkcontentEncoding" time="0.003" classname="com.qa.EmployeeAPI.TestCase.TC001_Get_All_Employees"/>
  <testcase name="checkResposeBody" time="0.002" classname="com.qa.EmployeeAPI.TestCase.TC001_Get_All_Employees"/>
  <testcase name="checkstatusLine" time="0.000" classname="com.qa.EmployeeAPI.TestCase.TC001_Get_All_Employees"/>
  <testcase name="checkContentType" time="0.001" classname="com.qa.EmployeeAPI.TestCase.TC001_Get_All_Employees">
    <failure type="java.lang.AssertionError" message="expected:&lt;application/json;charset=utf-8&gt; but was:&lt;text/html; charset=UTF-8&gt;">
      <![CDATA[java.lang.AssertionError: expected:<application/json;charset=utf-8> but was:<text/html; charset=UTF-8>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
at com.qa.EmployeeAPI.TestCase.TC001_Get_All_Employees.checkContentType(TC001_Get_All_Employees.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkContentType -->
  <testcase name="checkCookies" time="0.001" classname="com.qa.EmployeeAPI.TestCase.TC001_Get_All_Employees"/>
  <testcase name="checkStatusCode" time="0.002" classname="com.qa.EmployeeAPI.TestCase.TC001_Get_All_Employees"/>
</testsuite> <!-- com.qa.EmployeeAPI.TestCase.TC001_Get_All_Employees -->
